project_name: Build wireproxy
before:
  hooks:
    - go mod tidy -v
    RELEASE_VERSION: ${GITHUB_REF#refs/*/}
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
#      - linux
      - windows
#      - darwin
    goarch:
 #     - arm
 #     - arm64
      - 386
 #     - amd64
 #     - mips
 #     - mipsle
 #     - s390x
 #     - riscv64
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/wireproxy/
    binary: wireproxy
universal_binaries:
  - name_template: "wireproxy"
    replace: false
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "wireproxy"
archives:
  - name_template: "wireproxy_echo ${{ env.RELEASE_VERSION }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
