name: Cross compile BoringTun

on:
  workflow_dispatch:

jobs:
  BoringTun:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v2
      - name: Git clone BoringTun
        run: |
          git clone https://github.com/cloudflare/boringtun
          cd boringtun
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin boringtun --all-features
