name: Cross compile BoringTun

on:
  workflow_dispatch:

jobs:
  BoringTun:
    name: Rust project
    runs-on: ubuntu-latest
    env:
      workdir: ./boringtun
    steps:
      - name: Check code
        uses: actions/checkout@v2
      - name: Git clone BoringTun
        run: |
          git clone https://github.com/cloudflare/boringtun "$workdir"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
