name: Cross compile BoringTun

on:
  workflow_dispatch:

jobs:
  BoringTun:
    name: Cross compile BoringTun
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v2
      - name: Git clone BoringTun
        run: |
          git clone https://github.com/cloudflare/boringtun
          cp -r boringtun/* .
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --bin boringtun-cli --all-features
          
      - name: Release binaries 
        uses: softprops/action-gh-release@v1
        with:
          tag_name: BoringTun
          files: ./target/release/boringtun-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
