name: "Build Glibc V2.28"

on:
  push:
    tags:
      - "*"

jobs:
  Building:
    name: "Build Glibc on CentOS 7"
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v2
 
    - name: Build make
      run: |
        yum -y install gcc bison make centos-release-scl wget
        yum -y install devtoolset-8-gcc
        yum -y install devtoolset-8-gcc-c++
        yum -y install devtoolset-8-binutils
        source /opt/rh/devtoolset-8/enable
        mkdir -p /opt/release/
        wget http://ftp.gnu.org/gnu/make/make-4.3.tar.gz
        tar -xzvf make-4.3.tar.gz
        cd make-4.3
        ./configure
        make
        make install
        echo y | cp -f ./make /usr/bin/
        cp ./make /opt/release/
        cd ~

    - name: Build glibc-2.28
      run: | 
        wget http://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
        tar -zxvf glibc-2.28.tar.gz
        mkdir -p ./glibc-2.28/build
        mkdir -p /opt/release/
        tar -czvf /opt/release/glibc-2.28.tar.gz ./glibc-2.28

    - name: Binaries Release
      uses: softprops/action-gh-release@v1
      with:
          files: /opt/release/*
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
