name: "Build Glibc V2.28"

on:
  workflow_dispatch:

jobs:
  Building:
    name: "Build Glibc on CentOS 7"
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v2
 
    - name: intall dependencies
      run: |
        yum -y install gcc bison make centos-release-scl wget
        yum -y install devtoolset-8-gcc
        yum -y install devtoolset-8-gcc-c++
        yum -y install devtoolset-8-binutils
        # source /opt/rh/devtoolset-8/enable
        scl enable devtoolset-8 bash
        wget -O /usr/bin/make https://github.com/fscarmen/tools/raw/main/make
 
    - name: build
      run: |
        wget http://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
        tar zxf glibc-2.28.tar.gz
        mkdir -p ./glibc-2.28/build; cd ./glibc-2.28/build
        ../configure --prefix=/usr --disable-profile --enable-add-ons --with-headers=/usr/include --with-binutils=/usr/bin
        make
        make install

    - name: check
      run: |
        strings /lib64/libc.so.6 | grep GLIBC_2.28
