name: "Build Glibc V2.28"

on:
  push:
    tags:
      - "*"

jobs:
  Building:
    name: "Build Glibc on CentOS 7"
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v2
 
    - name: build
      run: |
        yum -y install gcc bison make centos-release-scl wget
        yum -y install devtoolset-8-gcc
        yum -y install devtoolset-8-gcc-c++
        yum -y install devtoolset-8-binutils
        source /opt/rh/devtoolset-8/enable
        wget -O /usr/bin/make https://github.com/fscarmen/tools/raw/main/make
        wget http://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
        tar -zxvf glibc-2.28.tar.gz
        mkdir -p ./glibc-2.28/build
        mkdir -p /opt/release/
        ls ./glibc-2.28
        tar -czvf /opt/release/glibc-2.28.tar.gz ./glibc-2.28

    - name: Binaries Release
      uses: softprops/action-gh-release@v1
      with:
          files: /opt/release/*
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
