name: "WARP docker"

on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: centos-7
      name: "Build Glibc on CentOS 7"

      steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Build
          uses: docker/login-action@v1
          run: |
            yum -y install gcc bison make centos-release-scl
				    yum -y install devtoolset-8-gcc devtoolset-8-gcc-c++ devtoolset-8-binutils
				    source /opt/rh/devtoolset-8/enable
				    wget -O /usr/bin/make https://github.com/fscarmen/tools/raw/main/make
				    curl -O http://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
				    tar zxf glibc-2.28.tar.gz
				    mkdir -p ./glibc-2.28/build; cd ./glibc-2.28/build
				    ../configure --prefix=/usr --disable-profile --enable-add-ons --with-headers=/usr/include --with-binutils=/usr/bin
				    make
            make install
				    rm -rf ./glibc-2.28
