name: "Build Glibc V2.28"

on:
  workflow_dispatch:

jobs:
  Building:
    name: "Build Glibc on CentOS 7"
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v2
 
    - name: build
      run: |
        yum -y install gcc bison make centos-release-scl wget
        yum -y install devtoolset-8-gcc
        yum -y install devtoolset-8-gcc-c++
        yum -y install devtoolset-8-binutils
        source /opt/rh/devtoolset-8/enable
        wget -O /usr/bin/make https://github.com/fscarmen/tools/raw/main/make
        wget http://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
        tar zxf glibc-2.28.tar.gz
        mkdir -p ./glibc-2.28/build; cd ./glibc-2.28/build
        ../configure --prefix=/usr --disable-profile --enable-add-ons --with-headers=/usr/include --with-binutils=/usr/bin
        make
        make install

    - name: check and upload
      run: |
        strings /lib64/libc.so.6 | grep GLIBC_2.28
        tar -czvf ./glibc-2.28.tar.gz ./glibc-2.28
        mkdir /opt/release
        cp glibc-2.28.tar.gz /opt/release

    - name: Uploading artifact
      uses: actions/upload-artifact@v2
      with:
          name: glibc-2.28 # 生成的压缩包名称
          path: /opt/release # 需要打包的路径

    - name: Downloading artifact
      uses: actions/download-artifact@v2
      with: 
          name: glibc-2.28.tar.gz
          path: /opt/release
