name: "Build resolvconf"

on:
  workflow_dispatch:

jobs:
  Building:
    name: "Build on Ubuntu"
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yum -y install wegt gcc bison make centos-release-scl
        yum -y install devtoolset-8-gcc
        yum -y install devtoolset-8-gcc-c++
        yum -y install devtoolset-8-binutils
        mkdir -p /opt/release/

    - name: Build resolvconf v3.12.0
      run: |
        wget https://github.com/rsmarples/openresolv/archive/openresolv-3.12.0.tar.gz
        tar xzvf openresolv-3.12.0.tar.gz
        cd openresolv-openresolv-3.12.0
        ./configure
        make
        make install
        cp ./resolvconf /opt/release/

    - name: Release binaries 
      uses: softprops/action-gh-release@v1
      with:
          tag_name: resolvconf v3.12.0
          files: /opt/release/resolvconf
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
