name: "Build resolvconf"

on:
  workflow_dispatch:

jobs:
  Building:
    name: "Build on Ubuntu"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt -y install gcc bison make centos-release-scl
        sudo apt -y install devtoolset-8-gcc
        sudo apt -y install devtoolset-8-gcc-c++
        sudo apt -y install devtoolset-8-binutils
        sudo mkdir -p /opt/release/

    - name: Build resolvconf v3.12.0
      run: |
        sudo wget https://github.com/rsmarples/openresolv/archive/openresolv-3.12.0.tar.gz
        sudo tar xzvf openresolv-3.12.0.tar.gz
        cd openresolv-openresolv-3.12.0
        sudo ./configure
        sudo make
        sudo make install
        sudo cp ./resolvconf /opt/release/

    - name: Release binaries 
      uses: softprops/action-gh-release@v1
      with:
          tag_name: resolvconf v3.12.0
          files: /opt/release/resolvconf
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
