name: Build Wireguard-go

on:
  workflow_dispatch:

jobs:
  binaries:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Fetch Go version
        run: |
          GO_VERSION=1.18
          echo "go_version=$GO_VERSION" >> $GITHUB_ENV

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "${{ env.go_version }}"

      - name: Binaries Release
        run: |
            git clone https://git.zx2c4.com/wireguard-go
            cd wireguard-go
            go build -v -o "wireguard-go"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
