name: Build Wireguard-go

on:
  workflow_dispatch:

jobs:
  Build:
    name: Build Linux Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build wireguard-go
        run: |
          git clone https://git.zx2c4.com/wireguard-go
          cd wireguard-go
          go build -v -o "wireguard-go"
          mkdir release
          cp wireguard-go release/main
