name: Build Wireguard-go

on:
  push:
    tags:
      - "*"

jobs:
  binaries:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64, arm64, s390x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Fetch Go version
        run: |
            GO_VERSION=1.18
            echo "go_version=$GO_VERSION" >> $GITHUB_ENV
            mkdir -p /opt/release/
            git clone https://git.zx2c4.com/wireguard-go
            cd wireguard-go
            go build -v -o "/opt/release/wireguard-go-${{ matrix.goarch }}"
   
      - name: Release binaries 
        uses: softprops/action-gh-release@v1
        with:
            files: /opt/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
