name: Build Wireguard-go

on:
  push:
    tags:
      - "v*"

jobs:
  binaries:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"
          
      - name: Git clone
        run: |
          git clone https://git.zx2c4.com/wireguard-go
          cp .goreleaser.yml wireguard-go/

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          workdir: ./wireguard-go
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: ls
        run: |
          ls ./wireguard-go/
          
      - name: Release binaries 
        uses: softprops/action-gh-release@v1
        with:
          files: ./wireguard-go/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
