name: Build Wireguard-go

on:
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64 
        goos: [linux]
        goarch: [amd64, arm64]
#        exclude:  
#          - goarch: "386"
#            goos: darwin
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/test-binary"
          binary_name: "test-binary"

      - name: Building wireguard-go
        run: |
          git clone https://git.zx2c4.com/wireguard-go
          cd wireguard-go

      - name: Binaries Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
