name: Build Wireguard-go

on:
  push:
    tags:
      - "*"

jobs:
  binaries:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64, s390]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Fetch Go version
        run: |
          GO_VERSION=1.18

      - name: Build WireGuard-go
        run: |
            mkdir -p /opt/release/
            git clone https://git.zx2c4.com/wireguard-go

      - name: Setup Go environment
        uses: actions/setup-go@v3

      - uses: wangyoucao577/go-release-action@v1.25
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "latest"
          project_path: "./wireguard-go"
          binary_name: "wireguard-go-${{ matrix.goos }}-${{ matrix.goarch }}"
   
      - name: Release binaries 
        uses: softprops/action-gh-release@v1
        with:
            files: /opt/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
