name: Build Wireguard-go

on:
  push:
    tags:
      - "v*"

jobs:
  binaries:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64, s390x]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64, s390x
            goos: windows

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.2"
          
      - name: Git clone WireGuard-go
        run: |
          mkdir -p /opt/release/
          git clone https://git.zx2c4.com/wireguard-go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          project_path: "./wireguard-go"
          release_name: "wireguard-go"
          binary_name: "wireguard-go-${{ matrix.goos }}-${{ matrix.goarch }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
